// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZWiDsd13aCkCH-Mh0qbUDCdI-OSB0nxE',
    appId: '1:96394799062:web:db03e6466eac6654e16677',
    messagingSenderId: '96394799062',
    projectId: 'klc-control',
    authDomain: 'klc-control.firebaseapp.com',
    storageBucket: 'klc-control.appspot.com',
    measurementId: 'G-QW6MHHRMBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIuqFsSvUMSGS4bKJmwRl-M_8mxlNcRQY',
    appId: '1:96394799062:android:a4078b652413e3e9e16677',
    messagingSenderId: '96394799062',
    projectId: 'klc-control',
    storageBucket: 'klc-control.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaKaHi2Lu0v_nW1xU5xmZ5gYap_XMMFgQ',
    appId: '1:96394799062:ios:a3befb7f790a7e01e16677',
    messagingSenderId: '96394799062',
    projectId: 'klc-control',
    storageBucket: 'klc-control.appspot.com',
    iosClientId: '96394799062-32e7p1r0b8koi9og6tffpgnvrsngdoaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaKaHi2Lu0v_nW1xU5xmZ5gYap_XMMFgQ',
    appId: '1:96394799062:ios:a3befb7f790a7e01e16677',
    messagingSenderId: '96394799062',
    projectId: 'klc-control',
    storageBucket: 'klc-control.appspot.com',
    iosClientId: '96394799062-32e7p1r0b8koi9og6tffpgnvrsngdoaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.driverApp',
  );
}
